/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	knativev1 "github.com/camel-tooling/camel-dashboard-operator/pkg/apis/duck/knative/v1"
	scheme "github.com/camel-tooling/camel-dashboard-operator/pkg/client/knative/clientset/internalclientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServicesGetter has a method to return a ServiceInterface.
// A group's client should implement this interface.
type ServicesGetter interface {
	Services(namespace string) ServiceInterface
}

// ServiceInterface has methods to work with Service resources.
type ServiceInterface interface {
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*knativev1.Service, error)
	List(ctx context.Context, opts metav1.ListOptions) (*knativev1.ServiceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	ServiceExpansion
}

// services implements ServiceInterface
type services struct {
	*gentype.ClientWithList[*knativev1.Service, *knativev1.ServiceList]
}

// newServices returns a Services
func newServices(c *ServingV1Client, namespace string) *services {
	return &services{
		gentype.NewClientWithList[*knativev1.Service, *knativev1.ServiceList](
			"services",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *knativev1.Service { return &knativev1.Service{} },
			func() *knativev1.ServiceList { return &knativev1.ServiceList{} },
		),
	}
}
