name: Nightly

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  release-nightly:
    strategy:
      fail-fast: false
      matrix:
        ref-branch: [main]

    if: github.repository == 'camel-tooling/camel-dashboard-operator'
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.ref-branch }}
        persist-credentials: false
        submodules: recursive
    - name: Release nightly ${{ matrix.ref-branch }} branch
      uses: ./.github/actions/release
      with:
        version: "latest"
        user: "${{ secrets.QUAY_USERNAME }}"
        token: "${{ secrets.QUAY_ROBOT_TOKEN }}"
